import Head from 'next/head';

import NewEvent from '@components/Admin/EventPanel/NewEvent';
import Sidebar from "@components/Admin/Sidebar";

export default function NuevoEvento() {
    return (
      <>
        <Head>
          <title>Admin - Nuevo evento</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/simple_logo_red.svg" />
        </Head>
        <main>
            <Sidebar />
            <NewEvent/>
        </main>
      </>
    )
  }