import Head from 'next/head';

import Sidebar from "@components/Admin/Sidebar";

import InventoryPanel from '@components/Admin/InventoryPanel';

export default function PanelInventario() {
    return (
        <>
            <Head>
                <title>Admin - Mi Bicla</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/simple_logo_red.svg" />
            </Head>
            <Sidebar />
            <InventoryPanel />
        </>
    )
}
