import Head from 'next/head';
import Navbar from '@components/BasicElements/Navbar';
import EventsPage from '@components/EventsPage';
import Footer from '@components/BasicElements/Footer';

import axios from "@utils/axios";

import getConfig from 'next/config';
const { publicRuntimeConfig } = getConfig();

import { mockEventList } from "@utils/mocks";

export default function Eventos({ events }) {
  return (
    <>
      <Head>
        <title>Mi Bicla - Eventos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/simple_logo_red.svg" />
      </Head>
      <main>
        <Navbar></Navbar>
        <EventsPage events={events}></EventsPage>
        <Footer></Footer>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  if (publicRuntimeConfig.env === "prod" || 
    publicRuntimeConfig.env === "local") {
    const { data } = await axios.get('/events');
    return { 
      props: { 
          events: data
      }   
    }
  } else {
    return {
      props: {
        events: mockEventList
      }
    }
  }
}