import Head from 'next/head';
import Navbar from '@components/LandingPage/Navbar';
import EventsPage from '@components/EventsPage';

import axios from "@utils/axios";

export default function Eventos({ events }) {
  console.log(events);
  return (
    <>
      <Head>
        <title>Mi Bicla - Eventos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/simple_logo_red.svg" />
      </Head>
      <main>
        <Navbar></Navbar>
        <EventsPage events={events}></EventsPage>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { data } = await axios.get('/events');
  return { 
    props: { 
        events: data
    }   
  }
}