import Head from 'next/head';

import StoreMainPage from '@components/Store/StoreMainPage/StoreMainPage';
import StoreNavbar from '@components/Store/StoreNavbar/StoreNavbar';

export default function Inventario() {
    return (
        <>
            <Head>
                <title>Mi Bicla - Inventario</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/simple_logo_red.svg" />
            </Head>
            <StoreNavbar></StoreNavbar>
            <StoreMainPage></StoreMainPage>
        </>
    )
}