import Head from 'next/head';

import Register from '@components/AuthComponents/Register';

import axios from "@utils/axios";

export default function Registro({ email }) {
    return (
        <>
            <Head>
                <title>Mi Bicla</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/simple_logo_red.svg" />
            </Head>
            <Register email={email}></Register>
        </>
    )
}

export async function getServerSideProps({ query }) {
    try {
        const { data } = await axios.get(`/users/validate_register_invitation/${query.token}`);
        return {
            props: {
                email: data
            }
        }
    } catch(err) {
        return {
            redirect: {
              destination: '/',
              permanent: false,
            },
          }
    }
  }